# Prerequisite: Environment variables EDBYUMUSERNAME and EDBYUMPASSWORD must be set up on the Ansible Controller 

# Usage: ansible-playbook prereqs/1-edb-prereqs.edb_repo_config.yml -i inventory.ini

- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    yumusername:  "{{ lookup('env','EDBYUMUSERNAME') }}"
    yumpassword: "{{ lookup('env','EDBYUMPASSWORD') }}"
        
  tasks:
    - name: Install latest EDB Repo
      yum:
        name: https://yum.enterprisedb.com/edbrepos/edb-repo-latest.noarch.rpm
        state: present

    - name: Update edb.repo with YUM repository credentials
      replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp1 }}"
        replace: "{{ item.replace }}"
      with_items:
        - { path: '/etc/yum.repos.d/edb.repo', regexp1: <username>, replace: "{{ yumusername }}" }
        - { path: '/etc/yum.repos.d/edb.repo', regexp1: <password>, replace: "{{ yumpassword}}" }