# Usage: ansible-playbook epas/edb-as-01.install_epas.yml -i inventory.ini --extra-vars "pgmajor=11"

# Works EPAS 10 and up

- hosts: epas-all
  become: yes
  become_user: root
  become_method: sudo
  vars:
      asmajor: "{{ pgmajor | default(11) }}"

  tasks:
    - name: Install EDB Postgres Advanced Server
      yum:
        name : ["edb-as{{ asmajor }}-server-core"]
        state: latest