# Usage: ansible-playbook eprs/edb-rs-01.install_eprs7.yml -i inventory.ini

- hosts: eprs-all
  become: yes
  become_user: root
  become_method: sudo
  vars:
        asmajor: "{{ pgmajor | default(11) }}"

  tasks:
    - name: Install EPAS client libraries, prerequisite for EPRS7 installation
      yum:
       name:  edb-as{{ asmajor }}-server-client
       state: latest

    - name: Ensure Java is installed
      yum:
       name: java
       state: latest

    - name: Install EDB Replication Server 7
      yum:
        name : ["edb-rs*"]
        state: latest
