# Usage: ansible-playbook eprs/edb-rs-04.init_leader_eprs7.yml -i inventory.ini --extra-vars "rspwd=adm1n"

- hosts: eprs-leader
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars:
        rspassword: "{{ rspwd }}"

  tasks:

    - name: Ensure pip is installed for module pre-requisites...
      easy_install:
        name: pip
        state: latest

    - name: Install expects module pre-requisites...
      easy_install:
        name: pexpect

    - name: Setting up .ngxpass, since -savepassword is not
      blockinfile:
        create: yes
        mode: 0600
        marker: "# {mark} Ansible Managed .NGXPASS File"
        dest: /opt/edb/.ngxpass
        block: |
          {{ansible_default_ipv4.address}}:8082:admin:{{ rspassword }}

    - name: Join the EPRS Network as Leader Node
      shell: /bin/bash -c "/usr/edb/rs-7.0/client/bin/runRepCLI.sh -joinnetwork -servername leaderNode -host {{ansible_default_ipv4.address}} -port 8082"

    - name: Set the EPRS Administrator Password...
      expect:
        command: /bin/bash -c "/usr/edb/rs-7.0/client/bin/runRepCLI.sh -setadminpassword -savepassword"
        responses:
          Question:
          (.*)Enter admin password(.*): "{{ rspassword }}"
#      no_log: true