# Usage:  ansible-playbook eprs/edb-rs.stop_eprs7.yml -i inventory.ini --extra-vars "host=eprs1"

- hosts: "{{ host }}"
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Starting EPRS7 as a system service
      systemd:
        name: edb-rs-server.service
        state: stopped
        enabled: yes