# This playbook assumes the command is being run on the leader node (Host=${Ansible Host entry for leader node}})
# Refer to the EPRS7 Getting Started Guide for setting the host IP and port of the leader service if running the client from a seperate server

# Usage: ansible-playbook eprs/edb-rs-05.join_network_eprs7.yml -i inventory.ini --extra-vars "joiningname=eprs2 joiningip=192.168.1.2"

- hosts: eprs-leader
  become: yes
  become_user: root
  become_method: sudo
  gather_facts: True
  vars:
        rsjoiningname: "{{ joiningname }}"
        rsjoiningip: "{{ joiningip }}"

  tasks:
    - name: Join the EPRS Network
      shell: /bin/bash -c "/usr/edb/rs-7.0/client/bin/runRepCLI.sh -joinnetwork -servername {{rsjoiningname}} -host {{ rsjoiningip }} -port 8082 -ngxpasspath /opt/edb/.ngxpass -user admin"