# Usage:  ansible-playbook edb-rs-03.start_eprs7.yml --extra-vars "host=eprs-servers"

- hosts: "{{ host }}"

  tasks:
    - name: Starting EPRS7 as a system service
      systemd:
        name: edb-rs-server.service
        state: started
        enabled: yes